name: Monitor Netflix Email

# Trigger the workflow manually from the GitHub UI
on:
  workflow_dispatch: # Allows manual triggering of the workflow
  # Schedule the workflow to run at specific times
  schedule:
    - cron: "*/5 11 * * 1-5" # Every 5 minutes from 11:00 to 11:55 UTC (7:00-7:55 PM UTC+8), weekdays
    - cron: "*/5 12 * * 1-5" # Every 5 minutes from 12:00 to 12:55 UTC (8:00-8:55 PM UTC+8), weekdays
    - cron: "0 13 * * 1-5" # Exactly 13:00 UTC (9:00 PM UTC+8), weekdays

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the version compatible with your script

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install Playwright
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run monitor.js
      - name: Run Monitor Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} # Store credentials in GitHub Secrets
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }} # Store token in GitHub Secrets
          BACKEND_URL: ${{ secrets.BACKEND_URL }} # Store backend URL in GitHub Secrets
          PORT: ${{ secrets.PORT }} # Store port in GitHub Secrets
          USER_EMAIL: ${{ secrets.USER_EMAIL }} # Store user email in GitHub Secrets
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }} # Store user password in GitHub Secrets
        run: node monitor.js
